version: '3'
services:
  api:
    build: .
  redis:
    image: "redis:alpine"
    restart:
        on-failure
  nginx:
    image: "staticfloat/nginx-certbot"
    ports: 
      - "80:80"
      - "443:443"
    environment: 
      CERTBOT_EMAIL: user@domain.com
      ENVSUBST_VARS: FQDN
      FQDN: api.domain.com
    volumes: 
      - "./nginx-config/obsidionapi.conf:/etc/nginx/user.conf.d:ro"
      - "letsencrypt:/etc/letsencrypt"

volumes: 
  letsencrypt: